function AddTextEntry(key, value)
	Citizen.InvokeNative(GetHashKey("ADD_TEXT_ENTRY"), key, value)
end

Citizen.CreateThread(function()
	AddTextEntry('MP_Christmas3_Tat_000', 'The Christmas Spirit')
	AddTextEntry('MP_Christmas3_Tat_001', 'Festive Reaper')
	AddTextEntry('MP_Christmas3_Tat_002', 'Skull Bauble')
	AddTextEntry('MP_Christmas3_Tat_003', 'Bony Snowman')
	AddTextEntry('MP_Christmas3_Tat_004', 'Herbal Bouquet')
	AddTextEntry('MP_Christmas3_Tat_005', 'Crash Krampus')
	AddTextEntry('MP_Christmas3_Tat_006', 'All In One Night')
	AddTextEntry('MP_Christmas3_Tat_007', 'A Little Present For You')
	AddTextEntry('MP_Christmas3_Tat_008', 'Gingerbread Steed')
	AddTextEntry('MP_Christmas3_Tat_009', 'Naughty Snow Globe')
	AddTextEntry('MP_Christmas3_Tat_010', 'Dude')
	AddTextEntry('MP_Christmas3_Tat_011', 'Fooligan Tribal')
	AddTextEntry('MP_Christmas3_Tat_012', 'Skull Jester')
	AddTextEntry('MP_Christmas3_Tat_013', 'Budonk-adonk')
	AddTextEntry('MP_Christmas3_Tat_014', 'Masked Machete Killer')
	AddTextEntry('MP_Christmas3_Tat_015', 'Killer')
	AddTextEntry('MP_Christmas3_Tat_016', 'Powwer')
	AddTextEntry('MP_Christmas3_Tat_017', 'Two Headed Beast')
	AddTextEntry('MP_Christmas3_Tat_018', 'Dudes')
	AddTextEntry('MP_Christmas3_Tat_019', 'Fooligan Jester')
	AddTextEntry('MP_Christmas3_Tat_020', 'Vile Smile')
	AddTextEntry('MP_Christmas3_Tat_021', 'Demon Skull Jester')
	AddTextEntry('MP_Christmas3_Tat_022', 'Fatal Incursion Outline')
	AddTextEntry('MP_Christmas3_Tat_023', 'Many-Headed Beast')
	AddTextEntry('MP_Christmas3_Tat_024', 'Demon Stitches')
	AddTextEntry('MP_Christmas3_Tat_025', 'Collector')
	AddTextEntry('MP_Christmas3_Tat_026', 'Folligan Clown')
	AddTextEntry('MP_Christmas3_Tat_027', 'Orang-O-Tang Dude')
	AddTextEntry('MP_Christmas3_Tat_028', 'Dude Outline')
	AddTextEntry('MP_Christmas3_Tat_029', 'Orang-O-Tang Gray')
	AddTextEntry('MP_Christmas3_Tat_030', 'Dude Jester')
	AddTextEntry('MP_Christmas3_Tat_031', 'Sailor Fuku Killer')
	AddTextEntry('MP_Christmas3_Tat_032', 'Fooligan')
	AddTextEntry('MP_Christmas3_Tat_033', 'Fooligan Impotent Rage')
	AddTextEntry('MP_Christmas3_Tat_034', 'Zombie Head')
	AddTextEntry('MP_Christmas3_Tat_035', 'Erupting Skeleton')
	AddTextEntry('MP_Christmas3_Tat_036', 'B-Donk Now Crank It Later')
	AddTextEntry('MP_Christmas3_Tat_037', 'Orang-O-Tang Grenade')
	AddTextEntry('MP_Christmas3_Tat_038', 'Fool')
	AddTextEntry('MP_Christmas3_Tat_039', 'Jack Me')
	AddTextEntry('MP_Christmas3_Tat_040', 'Monkey')
	AddTextEntry('MP_Christmas3_Tat_041', 'Dragon')
	AddTextEntry('MP_Christmas3_Tat_042', 'Snake')
	AddTextEntry('MP_Christmas3_Tat_043', 'Goat')
	AddTextEntry('MP_Christmas3_Tat_044', 'Rat')
	AddTextEntry('MP_Christmas3_Tat_045', 'Rabbit')
	AddTextEntry('MP_Christmas3_Tat_046', 'Ox')
	AddTextEntry('MP_Christmas3_Tat_047', 'Pig')
	AddTextEntry('MP_Christmas3_Tat_048', 'Rooster')
	AddTextEntry('MP_Christmas3_Tat_049', 'Dog')
	AddTextEntry('MP_Christmas3_Tat_050', 'Horse')
	AddTextEntry('MP_Christmas3_Tat_051', 'Tiger')
end)
